student_homepage:
    path:     /student
    defaults: { _controller: StudentBundle:Default:index }

student_myhome:
    path:  /std_myhome
    defaults: { _controller: StudentBundle:Default:myhome }

student_runme:
    path:  /std_runme
    defaults: { _controller: StudentBundle:Default:runme }

student_runmetest:
    path: /std_runmetest
    defaults: { _controller: StudentBundle:Default:runmetest }

student_myclasses:
    path: /std_myclasses
    defaults: { _controller: StudentBundle:Studentclass:myclasses }

student_loadclassassignments:
    path: /std_load_class_assignments/{classid}
    defaults: { _controller: StudentBundle:Studentclass:load_class_assignments }

student_submitassignmentthroughclass:
    path: /std_submit_assignments_through_class/{assignmentid}
    defaults: { _controller: StudentBundle:Studentclass:submit_assignments_through_class }

student_runme_try:
    path:  /std_runme_try/{$text}
    defaults:  
          _controller: MainBundle:Default:writefile
          text: $text


