main_testrunp:
    path:     /runp
    defaults: { _controller: MainBundle:Default:index }

main_writefile:
    path:   /main_runfile
    defaults: { _controller: MainBundle:Default:runfile}

main_writetofile:
    path:   /main_writetofile
    defaults: { _controller: MainBundle:Default:writetofile}

main_login:
    path:   /apags
    defaults: { _controller: MainBundle:Login:login}

main_register:
    path:   /register
    defaults: { _controller: MainBundle:Login:register}