main_homepage:
    path:     /runp
    defaults: { _controller: MainBundle:Default:index }

main_writefile:
    path:   /main_runfile
    defaults: { _controller: MainBundle:Default:runfile}

main_writetofile:
    path:   /main_writetofile
    defaults: { _controller: MainBundle:Default:writetofile}